gem "dm-core", "0.10.1"
gem "dm-timestamps", "0.10.1"
gem "dm-types", "0.10.1"
gem "dm-migrations", "0.10.1"
gem "dm-aggregates", "0.10.1"
gem "dm-validations", "0.10.1"
gem "bcrypt-ruby", "2.0.5"
gem "uuidtools", "2.0.0"
gem "extlib", "0.9.13"
gem "data_objects", "0.10.0"
gem "do_sqlite3", "0.10.0"
gem "rake"
gem "haml", "2.2.2"
gem "thor", "0.9.9"
gem "addressable", "2.1.0"
gem "rack", "1.0.0"
gem "json", "1.1.9"
gem "sinatra", "0.9.4"
gem "sinatra-authorization", "1.0.0"
gem "sinatra-url-for", :git => "git://github.com/emk/sinatra-url-for.git"

# These are dependencies for the various notifiers. Uncomment as appropriate.
# = Email
# gem "sinatra-ditties"
# = IRC
# gem "shout-bot"
# = Campfire
# gem "broach"

# = Dependencies for the :dj builder
# gem "activerecord"
# gem "delayed_job", :git => "git://github.com/tobi/delayed_job.git"

# = Development dependencies.
only :test do
  source "http://gems.github.com"
  gem "ruby-debug"
  gem "sqlite3-ruby"
  gem "activerecord"
  gem "delayed_job", :git => "git://github.com/tobi/delayed_job.git"
  gem "rr"
  gem "mocha"
  gem "redgreen"
  gem "dm-sweatshop"
  gem "ParseTree"
  gem "randexp"
  gem "rack-test", "0.5.0"
  gem "rumbster"
  gem "nokogiri"
  gem "hpricot"
  gem "jeremymcanally-pending"
  gem "jeremymcanally-context"
  gem "foca-storyteller"
  gem "webrat"
  gem "shout-bot"
  gem "sinatra-ditties"
  gem "broach"
  gem "nap", :git => "git://github.com/qrush/nap.git"
  gem "webmock"
end
