#!/bin/sh
cat <<EOF
<!DOCTYPE html>
<html>
<head>
<title>Integrity | The easy and fun automated continuous integration server</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
<link href=integrity.css rel=stylesheet type="text/css">
</head>
<body>
<p><a href="http://github.com/integrity">
<img style="position: absolute; top: 0; right: 0; border: 0;"
src="http://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"
alt="Fork me on GitHub" /></a></p>
<div id=header>
<h1><a href="/">Integrity</a></h1>
<p>The easy and fun automated <strong>continuous integration</strong>
server</p>
</div>
<div id=content>
EOF
cat | asciidoc -s -
cat <<EOF
</div>
<div id=footer>
  <div class=credits>
    Integrity is &copy; 2008, 2009
    <a href="http://nicolassanguinetti.info">Nicolás Sanguinetti</a>
    and <a href="http://atonie.org">Simon Rozet</a>
  </div>
  <div class=links>
    <a href="http://integrity.lighthouseapp.com/projects/14308-integrity">Bugs / Support</a>
        |
    <a href="http://github.com/integrity/integrity">Source Code</a>
  </div>
</div>
<script type="text/javascript">
  //<![CDATA[
  var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
  document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
  //]]>
  </script>
  <script type="text/javascript">
    //<![CDATA[
      try {
      var pageTracker = _gat._getTracker("UA-6377994-1");
      pageTracker._trackPageview();
      } catch(err) {}
    //]]>
  </script>
  </body>
</html>
EOF
