require File.dirname(__FILE__) + "/expectations/be_a"
require File.dirname(__FILE__) + "/expectations/change"
require File.dirname(__FILE__) + "/expectations/have"
require File.dirname(__FILE__) + "/expectations/predicates"
require File.dirname(__FILE__) + "/expectations/have_tag"
